AWSTemplateFormatVersion: "2010-09-09"
Description: Serverless Contact Form - Lambda + S3 + SNS + API Gateway

Parameters:
  AppRegion:
    Type: String
    Default: us-east-1
    Description: AWS region for deployment
  NotificationEmail:
    Type: String
    Default: "adamwronowy@gmail.com"
  BucketName:
    Type: String
    Default: "contact-form-submissions"

Resources:

  ContactFormBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketName}-${AWS::AccountId}"

  ContactFormTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: contact-form-topic

  ContactFormSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref NotificationEmail
      TopicArn: !Ref ContactFormTopic

  ContactFormLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess

  ContactFormLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: contact-form-handler
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Role: !GetAtt ContactFormLambdaRole.Arn
      Code:
        S3Bucket: crowproject-bucket
        S3Key: lambda/contactForm/lambda_package.zip
      Environment:
        Variables:
          BUCKET_NAME: crowproject-bucket
          SNS_TOPIC_ARN: !Ref ContactFormTopic
      Timeout: 10



  ContactFormApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: contact-form-api
      ProtocolType: HTTP

  ContactFormIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ContactFormApi
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ContactFormLambda.Arn}/invocations
      PayloadFormatVersion: "2.0"

  ContactFormRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ContactFormApi
      RouteKey: "POST /contact"
      Target: !Sub integrations/${ContactFormIntegration}

  ContactFormPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ContactFormLambda
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ContactFormApi}/*/*"

  ContactFormStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref ContactFormApi
      StageName: "$default"
      AutoDeploy: true

Outputs:
  ContactFormApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ContactFormApi}.execute-api.${AWS::Region}.amazonaws.com/contact"
