AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for creating a Route 53 record set for a CloudFront Distribution.

Parameters:
  HostedZoneId:
    Description: "The ID of the Route 53 Hosted Zone for your domain."
    Type: String
  DomainName:
    Description: "The domain name to create a record for (e.g., crow-project.click)."
    Type: String
  CloudFrontDomainName:
    Description: "The domain name of the CloudFront distribution (e.g., d1234abcdef8.cloudfront.net)."
    Type: String

Resources:
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2   # stable id

Outputs:
  RecordName:
    Description: "The domain name for the record set"
    Value: !Ref DomainName
