AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for S3 bucket hosting a static website.


Resources:
  CrowProjectBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: crowproject-bucket-demo
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

Outputs:
  BucketName:
    Description: "The name of the S3 bucket."
    Value: !Ref CrowProjectBucket
  WebsiteURL:
    Description: "URL for the static website hosted on S3."
    Value: !GetAtt CrowProjectBucket.WebsiteURL