AWSTemplateFormatVersion: '2010-09-09'
Description: AWS WAF WebACL for CloudFront distribution

Resources:
  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: MyCloudFrontWebACL
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: myWebACL
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet

Outputs:
  WebACLArn:
    Description: The ARN of the Web ACL
    Value: !GetAtt WebACL.Arn
